# ARACNe output adapter

In [1]:
import os
import sys
import glob
import pandas as pd
import numpy as np

In [40]:
example_out_dir = "/cellar/users/aklie/projects/igvf/topic_grn_links/grn_inference/aracne/results/Bridge_Satpathy/balanced_genotype_microglia/0.05/raw/B6J"

In [43]:
adj_tsvs = glob.glob(os.path.join(example_out_dir, "**", "network.txt"))

In [51]:
adj = pd.DataFrame()
for adj_tsv in adj_tsvs:
    adj_df = pd.read_csv(adj_tsv, sep="\t")
    adj_df["aracne_regulator_type"] = os.path.basename(os.path.dirname(adj_tsv))
    adj = pd.concat([adj, adj_df])
adj.head()

  Regulator   Target        MI        pvalue aracne_regulator_type
0     Satb1    Cntn1  0.085102  1.016205e-07                    tf
1     Clock  B3galt1  0.066611  1.022478e-05                    tf
2     Myt1l      Tef  0.036784  1.022478e-05                    tf
3     Nfat5     Fut9  0.062037  7.726228e-04                    tf
4     Nr1d2    Nalf1  0.042112  7.726228e-04                    tf

In [52]:
adj.rename(
    columns={
        "Target": "target",
        "MI": "weight_unsigned",
        "pvalue": "p"},
    inplace=True
)

In [53]:
adj["weight_signed"] = np.nan

In [54]:
adj["weight_minmax_normalized"] = (adj["weight_unsigned"] - adj["weight_unsigned"].min()) / (adj["weight_unsigned"].max() - adj["weight_unsigned"].min())

In [55]:
adj["description"] = np.nan

In [56]:
adj["-logp"] = -np.log10(adj["p"])

In [57]:
adj.reset_index(inplace=True)
adj.rename(columns={"Regulator": "source"}, inplace=True)

In [58]:
adj = adj[["source", "target", "weight_signed", "weight_unsigned", "weight_minmax_normalized", "p", "-logp", "description", "aracne_regulator_type"]]

In [59]:
adj

,source,target,weight_signed,weight_unsigned,weight_minmax_normalized,p,-logp,description,aracne_regulator_type
0,Satb1,Cntn1,NaN,0.085102,0.106503,1.016205e-07,6.993019,NaN,tf
1,Clock,B3galt1,NaN,0.066611,0.075625,1.022478e-05,4.990346,NaN,tf
2,Myt1l,Tef,NaN,0.036784,0.025820,1.022478e-05,4.990346,NaN,tf
3,Nfat5,Fut9,NaN,0.062037,0.067988,7.726228e-04,3.112032,NaN,tf
4,Nr1d2,Nalf1,NaN,0.042112,0.034717,7.726228e-04,3.112032,NaN,tf
...,...,...,...,...,...,...,...,...,...
41426,Zdhhc18,Epha5,NaN,0.026411,0.008499,7.726228e-04,3.112032,NaN,tf
41427,Kdm5b,Adgrb3,NaN,0.090596,0.115676,1.016205e-07,6.993019,NaN,tf
41428,Zfp445,Dmd,NaN,0.050118,0.048086,1.022478e-05,4.990346,NaN,tf
41429,Foxo1,Strn,NaN,0.031048,0.016243,7.726228e-04,3.112032,NaN,tf
41430,Klf7,Dgki,NaN,0.047460,0.043647,7.726228e-04,3.112032,NaN,tf